In [80]:
import numpy as np
import pandas as pd

Importando os dados e definindo Letras maiúsculas para o título das colunas

In [81]:
df = pd.read_csv('data_microdados.csv')
df.columns = [x.upper() for x in df.columns]

C:\Users\DMV INFOR\AppData\Local\Temp\ipykernel_10432\504763570.py:1: DtypeWarning: Columns (19,20,26,27,52,53,63,75,190,191,192,193,225,227,253,264,285,292,303,315,329,341) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data_microdados.csv')

Realizando a limpeza do dados

In [82]:
df = df.rename(columns={'P1_A': 'Idade',
                        'P1_A_1': 'Faixa idade'}).fillna(0).drop('P0', axis=1)
df.head()

,Idade,Faixa idade,P1_B,P1_C,P1_D,P1_E,P1_F,P1_G,P1_I,P1_I_1,...,P8_D_2,P8_D_3,P8_D_4,P8_D_5,P8_D_6,P8_D_7,P8_D_8,P8_D_9,P8_D_10,P8_D_11
0,26.0,25-29,Masculino,Branca,Não,0,0,True,São Paulo (SP),SP,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,25.0,25-29,Masculino,Branca,Não,0,0,True,Goiás (GO),GO,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,30.0,30-34,Masculino,Branca,Não,0,0,False,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,22.0,22-24,Feminino,Preta,Não,"Sim, acredito que a minha a experiência profis...","Aprovação em processos seletivos/entrevistas, ...",True,Minas Gerais (MG),MG,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,24.0,22-24,Feminino,Branca,Não,"Sim, acredito que a minha a experiência profis...",Quantidade de oportunidades de emprego/vagas r...,True,Santa Catarina (SC),SC,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0